/* Generated by build_deck.py — do not edit by hand.
   Vocabulary: open-anki-jlpt-decks (MIT).
   Pitch accent: Kanjium (CC BY-SA 4.0).
   Furigana: JmdictFurigana (CC BY-SA 4.0), from JMdict (EDRDG).
   pitch = -1 means the accent is unknown. */
window.JPVOCAB_CATS = [{"id":"grt","jp":"挨拶","en":"Greetings & set phrases"},{"id":"num","jp":"数字","en":"Numbers & counting"},{"id":"tim","jp":"時間","en":"Time & days"},{"id":"ppl","jp":"人・家族","en":"People & family"},{"id":"foo","jp":"食べ物","en":"Food & drink"},{"id":"pla","jp":"場所","en":"Places"},{"id":"obj","jp":"身の回り","en":"Everyday things"},{"id":"dir","jp":"方向・位置","en":"Directions & position"},{"id":"col","jp":"色・形","en":"Colours & shapes"},{"id":"bod","jp":"体","en":"The body & health"},{"id":"nat","jp":"自然","en":"Nature & weather"},{"id":"ani","jp":"動物・植物","en":"Animals & plants"},{"id":"tra","jp":"乗り物","en":"Getting around"},{"id":"hom","jp":"家","en":"Home & housework"},{"id":"stu","jp":"学校・仕事","en":"School & work"},{"id":"vrb","jp":"動詞","en":"Verbs"},{"id":"adj","jp":"形容詞","en":"Descriptions"},{"id":"abs","jp":"その他","en":"Ideas & everything else"}];
