/* Generated by build_deck.py — do not edit by hand.
   JLPT levels cross-referenced across three lists:
     open-anki-jlpt-decks (MIT), OpenJLPT (CC BY-SA 4.0),
     Bluskyo/JLPT_Vocabulary.
   Pitch accent: Kanjium (CC BY-SA 4.0). Furigana: JmdictFurigana
     (CC BY-SA 4.0), from JMdict (EDRDG).
   ps: exact = Kanjium matched word+reading; reading = matched the
   reading only; generated = rule-based guess, flagged in the app.
   src: how many of the three lists agreed on the level. */
window.JPVOCAB_CATS = [{"id":"grt","jp":"挨拶","en":"Greetings & set phrases"},{"id":"num","jp":"数字","en":"Numbers & counting"},{"id":"tim","jp":"時間","en":"Time & days"},{"id":"ppl","jp":"人・家族","en":"People & family"},{"id":"foo","jp":"食べ物","en":"Food & drink"},{"id":"pla","jp":"場所","en":"Places"},{"id":"obj","jp":"身の回り","en":"Everyday things"},{"id":"dir","jp":"方向・位置","en":"Directions & position"},{"id":"col","jp":"色・形","en":"Colours & shapes"},{"id":"bod","jp":"体","en":"The body & health"},{"id":"nat","jp":"自然","en":"Nature & weather"},{"id":"ani","jp":"動物・植物","en":"Animals & plants"},{"id":"tra","jp":"乗り物","en":"Getting around"},{"id":"hom","jp":"家","en":"Home & housework"},{"id":"stu","jp":"学校・仕事","en":"School & work"},{"id":"com","jp":"会話・気持ち","en":"Talking & feelings"},{"id":"lei","jp":"趣味・娯楽","en":"Leisure & media"},{"id":"gra","jp":"文法語","en":"Pronouns & connectors"},{"id":"vrb","jp":"動詞","en":"Verbs"},{"id":"adj","jp":"形容詞","en":"Descriptions"},{"id":"abs","jp":"その他","en":"Ideas & everything else"}];
